### ISSUE TITLE
Monthly files in the day directory

### ISSUE THREAD

**Issue by juliettelavoie** [Ouranosinc/miranda#47]
There are some monthly files in the `day` directory.

- `/simulations/raw/CMIP/CMIP6/global/NIMS-KMA/KACE-1-0-G/historical/r1i1p1f1/day/tasmax/tasmax_Amon_KACE-1-0-G_historical_r1i1p1f1_gr_185001-201412.nc`
- `/simulations/raw/ScenarioMIP/CMIP6/global/NIMS-KMA/KACE-1-0-G/ssp245/r1i1p1f1/day/tasmin/tasmin_Amon_KACE-1-0-G_ssp245_r1i1p1f1_gr_20150101-21001230.nc`
- `/simulations/raw/CMIP/CMIP6/global/NIMS-KMA/KACE-1-0-G/historical/r1i1p1f1/day/tasmin/tasmin_Amon_KACE-1-0-G_historical_r1i1p1f1_gr_185001-201412.nc`

**Comment by Zeitsperre** [comment]
Sounds good. All of these changes will be addressed next week. 

Also, just an FYI, but Miranda issues are open to the public, so we should probably remove internal server/disk names.

**Comment by juliettelavoie** [comment]
Thank you!

Oups my bad I thought it was private ! Removing it now.

**Comment by Zeitsperre** [comment]
I can see why those files showed up under `day`. Looks as though the metadata for these are wrong:
```
		:table_id = "day" ;
```
I could implement checking via time_freq with xclim, but it would seriously slow down the process. I'd want to maybe run a conditional check at the decoding-level (if found freq isn't in the filename, run the time_freq check to be sure → emit warnings). It shouldn't be super difficult to do.
