### ISSUE TITLE
CORDEX source and driving_model contain the institution names

### ISSUE THREAD

**Issue by aulemahal** [Ouranosinc/miranda#48]
I'm not sure if this is a bug or if it was a choice, but the cordex facets "driving_model" contains "driving_institution" and "source" contains "institution".

For example:
`simulations/raw/CMIP/CMIP5/CORDEX/NAM-22/CCCma-CanRCM4/CCCma-CanESM2/historical/r1i1p1/day/tasmax/tasmax_NAM-22_CCCma-CanESM2_historical_r1i1p1_CCCma-CanRCM4_r2_day_19500101-19501231.nc`

Instead of `CCCma-CanRCM4`, I would have expected `CCCma_CanRCM4` or `CanRCM4`. and instead of  `CCCma-CanESM2`, I would have expected `CCCma_CanESM2` or `CanESM2`.

The second choice implies using `CRCM5-UQAM` and `CRCM5-OUR` as on the cordex website, so I would prefer the first one.

**Comment by Zeitsperre** [comment]
This was a design decision. The `model` and `source` names are pulled directly from the controlled vocabulary used by WCRP/ESGF. Dropping the `institution` from the name would be a fair amount of work (would need to handle institutions with dashes already in their names; also, `CRCM5-OUR` and `CRCM5-UQAM` are different models (technically), so mixing them would not be a good idea.). Example: https://github.com/ES-DOC/pyessv-archive/blob/master/wcrp/cordex/driving-model/cccma-canesm2

If we want to change the dashes to underlines, that's something we should talk about tomorrow.
