### ISSUE TITLE
Two extra years in FGOALS-g3 historical

### ISSUE THREAD

**Issue by juliettelavoie** [Ouranosinc/miranda#70]
Normally, historical data stops on 2014-12-31 and the ssps start on 2015-01-01.

For `/datasets/simulation/raw/CMIP6/CMIP/global/CAS/FGOALS-g3/historical/`, historical stops on 2016-12-31, but the ssps still start on 2015-01-01. This breaks `xscen.search_data_catalogs` when using the argument `periods` because there are repeat years.

I suggest removing the files: `*_day_FGOALS-g3_historical_r1i1p1f1_gn_20150101-20151231.nc` and `*_day_FGOALS-g3_historical_r1i1p1f1_gn_20160101-20161231.nc`

**Comment by Zeitsperre** [comment]
Files have been pruned.
