### ISSUE TITLE
corrumpted file

### ISSUE THREAD

**Issue by DoMatte** [Ouranosinc/miranda#74]
Salut, il y a un fichier corrompu sur tank
simulation/raw/CMIP6/ScenarioMIP/global/CSIRO-ARCCSS/ACCESS-CM2/ssp585/r1i1p1f1/day/pr/pr_day_ACCESS-CM2_ssp585_r1i1p1f1_gn_20150101-20641231.nc

**Comment by Zeitsperre** [comment]
Merci Domnique, je vais enlever ce fichier.

Pour la prochaine fois, peux-tu éviter de mettre le nom de nos disques internes ? On ne veut pas publier nos adresses internes.

**Comment by Zeitsperre** [comment]
Fichier remplacé.
