### ISSUE TITLE
ValueError: Resulting object does not have monotonic global indexes along dimension time

### ISSUE THREAD

**Issue by DoMatte** [Ouranosinc/miranda#76]
Bonjour,
tas_Amon_FGOALS-g3_historical_r1i1p1f1_gn_201001-201612.nc overlap avec les ssp, peut-on le couper à 2014?

**Comment by Zeitsperre** [comment]
For provenance reasons, I don't modify existing netcdf files in-place. This is an issue that requires a better solution, one being to provide rechunked/zarr versions of our existing files. I need to carve some time out to plan this move properly.

In the meantime, are there workarounds that could serve your needs?

**Comment by aulemahal** [comment]
@DoMatte Je suis curieux : qu'est-ce qui arrive si tu édite le catalogue et que tu change le "date_end" pour que ça soit 201412 ? Est-ce que xscen plante ou bien est-ce que la concaténation se fait silencieusement?

**Comment by DoMatte** [comment]
@aulemahal, oui ça ça marche, mais il n'a pas à faire le switch au ssp, donc pas de problème d'overlap. Je me dis que peut-être la solution patché est de créer un catalog où mes historique et ssp sont extrait séparément pour ensuite les lire et les merger. Mais je me dis que ça serait bien si xscen pouvait gérer ça disons en spécifiant une année pivot par exemple ou que par défaut si on merge historique et ssp, l'overlap soit gérer.

**Comment by Zeitsperre** [comment]
The issue is temporarily resolved:
 - Original files were moved to `_tas_Amon_FGOALS-g3_historical_r1i1p1f1_gn_201001-201612.nc`
 - A temporal subset ending in 201412 was produced

Better solutions needed in the future.
