### ISSUE TITLE
Some daily CORDEX variables given at midnight

### ISSUE THREAD

**Issue by aulemahal** [Ouranosinc/miranda#86]
I haven't dug everywhere, but at least for `simulation/raw/CMIP5/CORDEX/NAM-44/UQAM/UQAM-CRCM5/CCCma-CanESM2/historical/r1i1p1/day/`, `tasmin` and `tasmax` are given at noon, while `pr` is given at midnight.

This fails `xscen`.  In  `extract_dataset`, we call  `to_dataset_dict` which opens all variables of a given frequency into the same dataset, without checking for this kind of issue. We do have a `ensure_correct_time` check, but it happens afterwards, when the duplicated time axis was already created by xarray. And so the test fails.

@RondeauG @juliettelavoie @Zeitsperre 
Is this an xscen bug or a data bug?

A solution in xscen would be to remove the variable union aggregation from the catalog esm spec and iterate over the variables individually. We already iterate over them, but we use the merged dataset as created by intake-esm.

EDIT: Another solution would to put the "ensure_correct_time" test and correction in the `preprocess` of `to_dataset_dict`, At least, that's going to be my patch fix for the moment.

**Comment by RondeauG** [comment]
I think this might be a `miranda` issue? AKA, fix it upstream.

As for a fix in `xscen`, would it be possible to simply move `ensure_correct_time` to a preprocess in our call to `to_dataset_dict()`?

**Comment by RondeauG** [comment]
It also makes me think of a similar problem if variables are not quite on the same grid (I've seen differences in something like the 10th decimal before). However in that case too, I'd favor fixing the file.

**Comment by aulemahal** [comment]
I don't know of any reason to have different times. Both midnight and noon are valid in a way, but our (pandas') standard for daily is midnight, so I don't see any reason to do differently.

@Zeitsperre Is this something miranda checks?

**Comment by Zeitsperre** [comment]
> @Zeitsperre Is this something miranda checks?

Not currently. Miranda checks for valid time frequencies (in metadata and via `infer_freq`). In the event that a file does have time starting at noon, I'd agree that it's a data bug, but I wouldn't correct the raw NetCDF for version tracking purposes.

I can see this being a type of correction that we could perform when converting data from non-standard to NetCDF/zarr though. We already do that for some of the nonstandard ERA5/Land variables. This should be something done in the `convert` module, alongside the metadata updates that we want to perform as well.

If we can map out how best to tackle this, I can add this to my existing branch that's focusing on this.

**Comment by aulemahal** [comment]
I am currently checking all CORDEX files and it is still running, but for now it seems that the problem is the inverse:
ALL cordex files have daily times at noon, except:
```
Mix midnight/noon simulation/raw/CMIP5/CORDEX/NAM-44/UQAM/UQAM-CRCM5/CCCma-CanESM2/rcp45/r1i1p1/day
  midnight vars: {'psl', 'snw', 'pr', 'rlds', 'prsn', 'ps', 'snd', 'rsus'}
Mix midnight/noon simulation/raw/CMIP5/CORDEX/NAM-44/UQAM/UQAM-CRCM5/CCCma-CanESM2/historical/r1i1p1/day
  midnight vars: {'psl', 'snw', 'rsds', 'rlus', 'pr', 'rlds', 'prsn', 'snd', 'rsus'}
```

**Comment by aulemahal** [comment]
@Zeitsperre  I confirm that the two datasets above are the only ones with this time-mixture disease. Everything else in the CMIP5/CORDEX folder seems to have the daily variables given at noon.
